[package]
name = "study_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
study_shared_types = { path= "../study_shared_types" }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"